name: jupyterlab-omnisci
channels:
  - conda-forge
dependencies:
  - pymapd>=0.12.0
  - nodejs
  - python>=3.7
  - jupyterlab<3.0.0,>=2.0.0
  - ipywidgets
  - pyyaml
  - vdom
  - tornado
  - jupyter-book
  - black
  - wheel
  - twine